### PR TITLE
Fix listBox demos

### LINKED ISSUE #67: Improve demos

### PR DESCRIPTION
**Pull request by shadikhani**
Fix #67

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-list-box-flow/68)

### CODE REVIEW

File: vaadin-list-box-flow-demo/src/main/java/com/vaadin/flow/component/listbox/demo/ListBoxView.java [hunk 1]
```diff
@@ -38,140 +43,166 @@
...
-                    .set("alignItems", "center");
+        addCard("Presentation", "Separators", listBox);
+    }
 
-            return layout;
+    private void customOptions() {
+        // begin-source-example
+        // source-example-heading: Customizing the label
+        ListBox<Information> listBox = new ListBox<>();
+        List<Information> list = Arrays.asList(
```
Comment (tomivirkki) [inline vaadin-list-box-flow-demo/src/main/java/com/vaadin/flow/component/listbox/demo/ListBoxView.java]: Same comment as [here](https://github.com/vaadin/vaadin-radio-button-flow/pull/114#discussion_r345108809). Use something more meaningful as the Bean's name

Comment (shadikhani) [reply vaadin-list-box-flow-demo/src/main/java/com/vaadin/flow/component/listbox/demo/ListBoxView.java]: Done.
